name: imaging_course_cp_day4_2024
channels:
  - defaults
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - conda-forge::zeroc-ice==3.6.5
  - h5py==3.7.0
  - pandas==1.5.3
  - pip
  - python==3.8.*
  - openjdk==11.0.13
  - conda-forge::wxpython==4.1.0
  - imageio==2.26.0
  - inflect==5.3.0
  - Jinja2==3.1.2
  - mahotas==1.4.13
  - scikit-image==0.20.0
  - scikit-learn==1.2.2
  - mysqlclient==1.4.6
  - pip:
    - omero-py==5.19.1
    - jupyter==1.0.0
    - git+https://github.com/CellProfiler/CellProfiler.git@v4.2.6