name: imaging_course_basic_day4_2024
channels:
  - bioconda
  - conda-forge
  - defaults
  - ome
dependencies:
  - python==3.9.*
  - numpy==1.26.4
  - scikit-image==0.22.0
  - ome::zeroc-ice36-python==3.6.5
  - pip
  - pip:
    - jupyter==1.0.0
    - ipywidgets<8  # required for display. Remove if you are not using notebook
    - omero-py==5.19.1
    - matplotlib==3.8.4
