name: imaging_course_stardist_day4_2024
channels:
  - bioconda
  - conda-forge
  - defaults
  - ome
dependencies:
  - python==3.9.*
  - conda-forge::ipywidgets==8.0.4
  - conda-forge::zeroc-ice==3.6.5
  - pip
  - pip:
    - omero-py==5.19.1
    - stardist==0.8.5
    - matplotlib==3.8.4
    - omero-cli-zarr==0.5.5
    - geojson==3.1.0
    - tensorflow-macos==2.12.0; platform_system == "Darwin"
    - tensorflow==2.12.0; platform_system != "Darwin"