name: imaging_course_cellpose_day4_2024
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python==3.9.*
  - conda-forge::zeroc-ice==3.6.5
  - conda-forge::ipywidgets==8.0.4
  - pip
  - pip:
    - jupyter==1.0.0
    - omero-py==5.19.1
    - cellpose==3.0.7
    - matplotlib==3.8.4
    - omero-cli-zarr==0.5.5
